---
- name: NPM install gloabl redis-commander
  npm: 
    name='redis-commander'
    global=yes

- name: Create supervisor configuration
  template:
    src='redis-commander.conf.j2'
    dest='/etc/supervisor/conf.d/redis-commander.conf'
  notify:
    - reload supervisor

- name: Allow http interface at port {{ redis_commander.port }}
  action: shell ufw allow {{ redis_commander.port }}

- name: Update supervisor configuration files dictionary
  shell: "{{ item }}"
  with_items:
    - supervisorctl reread
    - supervisorctl update
    - supervisorctl start redis_commander
  ignore_errors: True