---
- name: Install Debian packages
  apt: pkg={{item}} state=present
  with_items:
    - wget
    - curl
    - make
    - g++
    - gcc
    - libcurl4-openssl-dev
    - libsasl2-2
    - libsasl2-dev
    - libcurl3
