// Generated by CoffeeScript 1.4.0
(function() {
  var CLI, Commander, Completer, SocialCoffee, Thrift, readline;

  Thrift = require('./thrift/client');

  SocialCoffee = require('./version');

  readline = require('readline');

  Commander = require('commander');

  Completer = (function() {
    var COMPLETIONS;

    function Completer() {}

    COMPLETIONS = {
      friends: ['list'],
      friendship: ['create', 'remove'],
      quit: []
    };

    Completer.prototype.complete = function(line) {
      var commands, hits, line_part, suggestions;
      commands = line.trim().split(/\s+/i);
      if (commands.length === 2) {
        if (COMPLETIONS[commands[0]]) {
          hits = COMPLETIONS[commands[0]].filter(function(c) {
            return c.indexOf(commands[1]) === 0;
          });
          suggestions = hits.length > 0 ? hits : COMPLETIONS[commands[0]];
        } else {
          suggestions = [];
        }
        line_part = commands[1];
      } else if (commands.length === 1 && line[line.length - 1] === ' ') {
        suggestions = COMPLETIONS[commands[0]] ? COMPLETIONS[commands[0]] : [];
        line_part = commands[0];
      } else if (commands.length === 1) {
        hits = Object.keys(COMPLETIONS).filter(function(c) {
          return c.indexOf(commands[0]) === 0;
        });
        suggestions = hits.length > 0 ? hits : Object.keys(COMPLETIONS);
        line_part = commands[0];
      }
      return [suggestions, line_part];
    };

    return Completer;

  })();

  CLI = (function() {

    function CLI() {
      this.completer = new Completer;
    }

    CLI.prototype.handle_friends = function(commands) {
      return console.log(commands);
    };

    CLI.prototype.handle_friendship = function(commands) {
      return console.log(commands);
    };

    CLI.prototype.handle_quit = function() {
      console.log("bye bye ...");
      return this.cmd_interface.close();
    };

    CLI.prototype.start = function(args) {
      var cmd_options, options, prompt,
        _this = this;
      Commander.version("Social Coffee v" + SocialCoffee.version + " '" + SocialCoffee.codename + "'").option('-p, --port <n>', 'Port number', parseInt).option('-h, --host [host]', 'Host number', 'localhost').parse(args);
      options = {};
      options['host'] = Commander.host || 'localhost';
      options['port'] = Commander.port || 9090;
      this.client = Thrift.Client.connect(options.host, options.port);
      cmd_options = {
        input: process.stdin,
        output: process.stdout,
        completer: this.completer.complete
      };
      this.cmd_interface = readline.createInterface(cmd_options);
      prompt = "" + options.host + ":" + options.port + ">";
      this.cmd_interface.setPrompt(prompt, prompt.length);
      this.cmd_interface.on('line', function(line) {
        var commands;
        commands = line.trim().split(/\s+/i);
        switch (commands[0]) {
          case "friends":
            _this.handle_friends(commands);
            break;
          case "friendship":
            _this.handle_friendship(commands);
            break;
          case "quit":
            _this.handle_quit();
            break;
          default:
            if (line.trim().length > 0) {
              console.log('command unknown');
            }
        }
        return _this.cmd_interface.prompt();
      });
      this.cmd_interface.on('close', function() {
        return process.exit(0);
      });
      return this.cmd_interface.prompt();
    };

    return CLI;

  })();

  module.exports = CLI;

}).call(this);
