// Generated by CoffeeScript 1.4.0
(function() {
  var CLI, Command, Commander, Completer, CreateFriendshipCommand, ListFriendsCommand, PingCommand, QuitCommand, RemoveFriendshipCommand, ServerCountersCommand, ServerInfoCommand, ServerOptionsCommand, SocialCoffee, Thrift, readline,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Thrift = require('./thrift/client');

  SocialCoffee = require('./version');

  readline = require('readline');

  Commander = require('commander');

  Completer = (function() {
    var COMPLETIONS;

    function Completer() {}

    COMPLETIONS = {
      friends: ['list'],
      friendship: ['create', 'remove'],
      server: ['info', 'counters', 'options'],
      quit: [],
      ping: []
    };

    Completer.prototype.complete = function(line) {
      var commands, hits, line_part, suggestions;
      commands = line.trim().split(/\s+/i);
      if (commands.length === 2) {
        if (COMPLETIONS[commands[0]]) {
          hits = COMPLETIONS[commands[0]].filter(function(c) {
            return c.indexOf(commands[1]) === 0;
          });
          suggestions = hits.length > 0 ? hits : COMPLETIONS[commands[0]];
        } else {
          suggestions = [];
        }
        line_part = commands[1];
      } else if (commands.length === 1 && line[line.length - 1] === ' ') {
        suggestions = COMPLETIONS[commands[0]] ? COMPLETIONS[commands[0]] : [];
        line_part = commands[0];
      } else if (commands.length === 1) {
        hits = Object.keys(COMPLETIONS).filter(function(c) {
          return c.indexOf(commands[0]) === 0;
        });
        suggestions = hits.length > 0 ? hits : Object.keys(COMPLETIONS);
        line_part = commands[0];
      }
      return [suggestions, line_part];
    };

    return Completer;

  })();

  Command = (function() {

    function Command(context) {
      this.print = __bind(this.print, this);
      this.context = context;
    }

    Command.prototype.prompt = function() {
      return this.context.prompt();
    };

    Command.prototype.print = function(error, result) {
      if (error) {
        console.log("error occurred: " + error.message);
      } else {
        console.log(result);
      }
      return this.prompt();
    };

    Command.prototype.execute = function(commands) {
      return console.log(commands);
    };

    return Command;

  })();

  QuitCommand = (function(_super) {

    __extends(QuitCommand, _super);

    function QuitCommand() {
      return QuitCommand.__super__.constructor.apply(this, arguments);
    }

    QuitCommand.prototype.execute = function(commands) {
      console.log("bye bye ...");
      return this.context.close();
    };

    return QuitCommand;

  })(Command);

  PingCommand = (function(_super) {

    __extends(PingCommand, _super);

    function PingCommand() {
      return PingCommand.__super__.constructor.apply(this, arguments);
    }

    PingCommand.prototype.execute = function(commands) {
      return Thrift.Client.client.ping(this.print);
    };

    return PingCommand;

  })(Command);

  ServerInfoCommand = (function(_super) {

    __extends(ServerInfoCommand, _super);

    function ServerInfoCommand() {
      return ServerInfoCommand.__super__.constructor.apply(this, arguments);
    }

    ServerInfoCommand.prototype.execute = function(commands) {
      return Thrift.Client.client.getName(this.print);
    };

    return ServerInfoCommand;

  })(Command);

  ServerCountersCommand = (function(_super) {

    __extends(ServerCountersCommand, _super);

    function ServerCountersCommand() {
      return ServerCountersCommand.__super__.constructor.apply(this, arguments);
    }

    ServerCountersCommand.prototype.execute = function(commands) {
      return Thrift.Client.client.getCounters(this.print);
    };

    return ServerCountersCommand;

  })(Command);

  ServerOptionsCommand = (function(_super) {

    __extends(ServerOptionsCommand, _super);

    function ServerOptionsCommand() {
      return ServerOptionsCommand.__super__.constructor.apply(this, arguments);
    }

    ServerOptionsCommand.prototype.execute = function(commands) {
      return Thrift.Client.client.getOptions(this.print);
    };

    return ServerOptionsCommand;

  })(Command);

  ListFriendsCommand = (function(_super) {

    __extends(ListFriendsCommand, _super);

    function ListFriendsCommand() {
      return ListFriendsCommand.__super__.constructor.apply(this, arguments);
    }

    ListFriendsCommand.prototype.execute = function(commands) {
      var id;
      if (commands.length === 3) {
        id = parseInt(commands[2]);
        if (isNaN(id)) {
          console.log("error occurred: argument must be a positive number");
          return this.prompt();
        }
        return Thrift.Client.client.get_friends(id, this.print);
      }
    };

    return ListFriendsCommand;

  })(Command);

  CreateFriendshipCommand = (function(_super) {

    __extends(CreateFriendshipCommand, _super);

    function CreateFriendshipCommand() {
      return CreateFriendshipCommand.__super__.constructor.apply(this, arguments);
    }

    CreateFriendshipCommand.prototype.execute = function(commands) {
      var usera, userb,
        _this = this;
      if (commands.length === 4) {
        usera = parseInt(commands[2]);
        userb = parseInt(commands[3]);
        if (isNaN(usera) || isNaN(userb)) {
          console.log("error occurred: both of arguments must be positive numbers");
          return this.prompt();
        }
        return Thrift.Client.client.create_friendship(usera, userb, function(err, created) {
          if (err) {
            console.log("error occurred: " + err.message);
          } else {
            console.log("friendship newely created: " + created);
          }
          return _this.prompt();
        });
      }
    };

    return CreateFriendshipCommand;

  })(Command);

  RemoveFriendshipCommand = (function(_super) {

    __extends(RemoveFriendshipCommand, _super);

    function RemoveFriendshipCommand() {
      return RemoveFriendshipCommand.__super__.constructor.apply(this, arguments);
    }

    RemoveFriendshipCommand.prototype.execute = function(commands) {
      var usera, userb,
        _this = this;
      if (commands.length === 4) {
        usera = parseInt(commands[2]);
        userb = parseInt(commands[3]);
        if (isNaN(usera) || isNaN(userb)) {
          console.log("error occurred: both of arguments must be positive numbers");
          return this.prompt();
        }
        return Thrift.Client.client.remove_friendship(usera, userb, function(err, removed) {
          if (err) {
            console.log("error occurred: " + err.message);
          } else {
            console.log("friendship just removed: " + removed);
          }
          return _this.prompt();
        });
      }
    };

    return RemoveFriendshipCommand;

  })(Command);

  CLI = (function() {

    function CLI() {
      this.completer = new Completer;
    }

    CLI.prototype.start = function(args) {
      var cmd_options, options, prompt,
        _this = this;
      Commander.version("Social Coffee v" + SocialCoffee.version + " '" + SocialCoffee.codename + "'").option('-p, --port <n>', 'Port number', parseInt).option('-h, --host [host]', 'Host number', 'localhost').parse(args);
      options = {};
      options['host'] = Commander.host || 'localhost';
      options['port'] = Commander.port || 9090;
      cmd_options = {
        input: process.stdin,
        output: process.stdout,
        completer: this.completer.complete
      };
      this.cmd_interface = readline.createInterface(cmd_options);
      prompt = "" + options.host + ":" + options.port + ">";
      this.cmd_interface.setPrompt(prompt, prompt.length);
      this.cmd_interface.on('SIGINT', function() {
        return _this.cmd_interface.question('Are you sure you want to exit? [yes|no] ', function(answer) {
          if (answer.match(/^y(es)?$/i)) {
            new QuitCommand(_this.cmd_interface).execute();
          }
          return _this.cmd_interface.prompt();
        });
      });
      this.cmd_interface.on('line', function(line) {
        var commands;
        commands = line.trim().split(/\s+/i);
        switch (commands[0]) {
          case 'friends':
            if (commands.length > 1 && commands[1] === 'list') {
              return new ListFriendsCommand(_this.cmd_interface).execute(commands);
            }
            break;
          case 'friendship':
            if (commands.length > 1) {
              switch (commands[1]) {
                case 'create':
                  return new CreateFriendshipCommand(_this.cmd_interface).execute(commands);
                case 'remove':
                  return new RemoveFriendshipCommand(_this.cmd_interface).execute(commands);
              }
            }
            break;
          case 'server':
            if (commands.length > 1) {
              switch (commands[1]) {
                case 'info':
                  return new ServerInfoCommand(_this.cmd_interface).execute(commands);
                case 'counters':
                  return new ServerCountersCommand(_this.cmd_interface).execute(commands);
                case 'options':
                  return new ServerOptionsCommand(_this.cmd_interface).execute(commands);
              }
            }
            break;
          case 'ping':
            return new PingCommand(_this.cmd_interface).execute(commands);
          case 'quit':
          case 'exit':
            return new QuitCommand(_this.cmd_interface).execute(commands);
          default:
            if (line.trim().length > 0) {
              console.log('command unknown');
            }
            return _this.cmd_interface.prompt();
        }
      });
      this.cmd_interface.on('close', function() {
        Thrift.Client.close();
        return process.exit(0);
      });
      Thrift.Client.connect(options.host, options.port, function() {
        return _this.cmd_interface.prompt();
      });
      return this.cmd_interface.prompt();
    };

    return CLI;

  })();

  module.exports = CLI;

}).call(this);
