// Generated by CoffeeScript 1.4.0
(function() {
  var Config, Environment, KnownPath, assert, fs, logger, path, yaml,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Environment = require('./environment');

  KnownPath = require('./known_path');

  path = require('path');

  fs = require('fs');

  assert = require('assert');

  yaml = require('js-yaml');

  logger = require('winston');

  Config = (function() {

    function Config() {}

    Config.query_files = function() {
      var all_file_names;
      all_file_names = fs.readdirSync(KnownPath.config);
      return this.file_names = all_file_names.filter(function(file_name) {
        return file_name.match(/\S*.yaml$/i);
      });
    };

    Config.sanitize = function() {
      assert(this.file_names && this.file_names.length > 0, "No configuration files found");
      return assert(__indexOf.call(this.file_names, 'db.yaml') >= 0, "Database configuration file (db.yaml) not found");
    };

    Config.load_yaml = function(file_name) {
      var doc, file_path, yaml_content;
      file_path = path.join(KnownPath.config, file_name);
      yaml_content = fs.readFileSync(file_path, 'utf8');
      try {
        doc = yaml.safeLoad(yaml_content);
      } catch (e) {
        logger.error(e);
        logger.error("Failed to parse '" + file_name + "' file content");
        process.exit(1);
      }
      assert(doc && doc[Environment.current], "Configuration file '" + file_name + "' requires '" + Environment.current + "' environment configuration to be specified.");
      return doc;
    };

    Config.announce = function() {
      var base_name, doc, file_name, _i, _len, _ref, _results;
      _ref = this.file_names;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        file_name = _ref[_i];
        logger.info("Processing configuration file '" + file_name + "'");
        doc = this.load_yaml(file_name);
        base_name = path.basename(file_name, '.yaml');
        logger.info("One can access configuration of '" + file_name + "' with 'Config." + base_name + "' syntax.");
        _results.push(this[base_name] = doc[Environment.current]);
      }
      return _results;
    };

    Config.initialize = function() {
      this.query_files();
      this.sanitize();
      return this.announce();
    };

    return Config;

  })();

  module.exports = Config;

}).call(this);
