// Generated by CoffeeScript 1.4.0
(function() {
  var Commander, Server, SocialCoffee, options, server;

  SocialCoffee = require('./version');

  Server = require('./server');

  Commander = require('commander');

  Commander.version("Social Coffee v" + SocialCoffee.version + " '" + SocialCoffee.codename + "'").option('-p, --port <n>', 'Port number', parseInt).parse(process.argv);

  options = {};

  options['port'] = Commander.port || 3000;

  server = new Server;

  server.start(options);

}).call(this);
