// Generated by CoffeeScript 1.4.0
(function() {
  var KnownPath, path;

  path = require('path');

  KnownPath = (function() {
    var subpath, _i, _len, _ref;

    function KnownPath() {}

    KnownPath.root = path.join(__dirname, '..');

    _ref = ['bin', 'config', 'node_modules', 'src', 'log', 'test', 'tmp'];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      subpath = _ref[_i];
      KnownPath[subpath] = path.join(KnownPath.root, subpath);
    }

    KnownPath.pids = path.join(KnownPath.tmp, 'pids');

    return KnownPath;

  })();

  module.exports = KnownPath;

}).call(this);
