#
# Autogenerated by Thrift Compiler (1.0.0-dev)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'social_coffee_service_types'

module SocialCoffee
  module Thrift
    SOCIAL_COFFEE_VERSION_MAJOR = 1

    SOCIAL_COFFEE_VERSION_MINOR = 0

  end
end
