// Generated by CoffeeScript 1.4.0
(function() {
  var FacebookBase, SocialCoffee, logger, ttypes;

  SocialCoffee = require('../version');

  ttypes = require('./fb303_types');

  logger = require('winston');

  FacebookBase = (function() {

    function FacebookBase() {}

    FacebookBase.counters = {};

    FacebookBase.options = {};

    FacebookBase.alive = Date.now();

    FacebookBase.name = "SocialCoffee - v" + SocialCoffee.version + " (" + SocialCoffee.codename + ")";

    FacebookBase.getName = function(result) {
      return result(null, this.name);
    };

    FacebookBase.getVersion = function(result) {
      return result(null, SocialCoffee.version);
    };

    FacebookBase.getStatus = function(result) {
      return result(null, ttypes.fb_status.ALIVE);
    };

    FacebookBase.getStatusDetails = function(result) {
      return result(null, "service is up and running");
    };

    FacebookBase.aliveSince = function(result) {
      return result(null, this.alive);
    };

    FacebookBase.getCounters = function(result) {
      return result(null, this.counters);
    };

    FacebookBase.getCounter = function(key, result) {
      return result(null, (this.counters[key] != null ? this.counters[key] : 0));
    };

    FacebookBase.getCpuProfile = function(profileDurationInSec, result) {
      return result(null, "");
    };

    FacebookBase.resetCounter = function(key) {
      return this.counters[key] = 0;
    };

    FacebookBase.incrementCounter = function(key) {
      return this.counters[key] = (this.counters[key] != null ? this.counters[key] : 0) + 1;
    };

    FacebookBase.deleteCounter = function(key) {
      return delete this.counters[key];
    };

    FacebookBase.setOption = function(key, value, result) {
      this.options[key] = value;
      return result(null);
    };

    FacebookBase.getOption = function(key, result) {
      return result(null, (this.options[key] != null ? this.options[key] : ""));
    };

    FacebookBase.getOptions = function(result) {
      return result(null, this.options);
    };

    FacebookBase.reinitialize = function() {
      return logger.warn("Reinitialization request just came. Skipping ...");
    };

    FacebookBase.shutdown = function() {
      return logger.warn("Shutdown request just came. Skipping ...");
    };

    return FacebookBase;

  })();

  module.exports = FacebookBase;

}).call(this);
