//
// Autogenerated by Thrift Compiler (1.0.0-dev)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('node-thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = module.exports = {};
ttypes.fb_status = {
  'DEAD' : 0,
  'STARTING' : 1,
  'ALIVE' : 2,
  'STOPPING' : 3,
  'STOPPED' : 4,
  'WARNING' : 5
};
