// Generated by CoffeeScript 1.4.0
(function() {
  var FacebookBase, Friendship, ttypes,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ttypes = require('./social_coffee_service_types');

  FacebookBase = require('./facebook_base_handler');

  Friendship = require('../friendship');

  SocialCoffee.Thrift.Handler = (function(_super) {

    __extends(Handler, _super);

    function Handler() {
      return Handler.__super__.constructor.apply(this, arguments);
    }

    Handler.failure = function(error, result) {
      var ex;
      ex = new ttypes.SocialException();
      ex.message = error.message;
      return result(ex);
    };

    Handler.success = function(value, result) {
      return result(null, value);
    };

    Handler.ping = function(result) {
      return result(null, "pong");
    };

    Handler.get_friends = function(id, result) {
      return Friendship.select(id, function(error, friends) {
        if (error) {
          return Handler.failure(error, result);
        } else {
          return Handler.success(friends, result);
        }
      });
    };

    Handler.create_friendship = function(usera, userb, result) {
      return Friendship.create(usera, userb, function(error, created) {
        if (error) {
          return Handler.failure(error, result);
        } else {
          return Handler.success(created, result);
        }
      });
    };

    Handler.remove_friendship = function(usera, userb, result) {
      return Friendship.remove(usera, userb, function(error, removed) {
        if (error) {
          return Handler.failure(error, result);
        } else {
          return Handler.success(removed, result);
        }
      });
    };

    return Handler;

  }).call(this, FacebookBase);

  exports.Handler = SocialCoffee.Thrift.Handler;

}).call(this);
