// Generated by CoffeeScript 1.4.0
(function() {
  var Friendship, ttypes;

  ttypes = require('./social_coffee_service_types');

  Friendship = require('../friendship');

  SocialCoffee.Thrift.Handler = (function() {

    function Handler() {}

    Handler.failure = function(error, result) {
      var ex;
      ex = new ttypes.SocialException();
      ex.message = error.message;
      return result(ex);
    };

    Handler.success = function(value, result) {
      return result(null, value);
    };

    Handler.ping = function(result) {
      return result(null, "pong");
    };

    Handler.get_friends = function(id, result) {
      return Friendship.select(id, function(error, friends) {
        if (error) {
          return Handler.failure(error, result);
        } else {
          return Handler.success(friends, result);
        }
      });
    };

    Handler.create_friendship = function(usera, userb, result) {
      return Friendship.create(usera, userb, function(error, created) {
        if (error) {
          return Handler.failure(error, result);
        } else {
          return Handler.success(created, result);
        }
      });
    };

    Handler.remove_friendship = function(usera, userb, result) {
      return Friendship.remove(usera, userb, function(error, removed) {
        if (error) {
          return Handler.failure(error, result);
        } else {
          return Handler.success(removed, result);
        }
      });
    };

    return Handler;

  }).call(this);

  exports.Handler = SocialCoffee.Thrift.Handler;

}).call(this);
