//
// Autogenerated by Thrift Compiler (1.0.0-dev)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('node-thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./social_coffee_service_types');
//HELPER FUNCTIONS AND STRUCTURES

SocialCoffee.Thrift.SocialCoffeeService_get_friends_args = function(args) {
  this.id = null;
  if (args) {
    if (args.id !== undefined) {
      this.id = args.id;
    }
  }
};
SocialCoffee.Thrift.SocialCoffeeService_get_friends_args.prototype = {};
SocialCoffee.Thrift.SocialCoffeeService_get_friends_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.id = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SocialCoffee.Thrift.SocialCoffeeService_get_friends_args.prototype.write = function(output) {
  output.writeStructBegin('SocialCoffeeService_get_friends_args');
  if (this.id !== null && this.id !== undefined) {
    output.writeFieldBegin('id', Thrift.Type.I32, 1);
    output.writeI32(this.id);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

SocialCoffee.Thrift.SocialCoffeeService_get_friends_result = function(args) {
  this.success = null;
  this.ex = null;
  if (args instanceof ttypes.SocialException) {
    this.ex = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.ex !== undefined) {
      this.ex = args.ex;
    }
  }
};
SocialCoffee.Thrift.SocialCoffeeService_get_friends_result.prototype = {};
SocialCoffee.Thrift.SocialCoffeeService_get_friends_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size0 = 0;
        var _rtmp34;
        this.success = [];
        var _etype3 = 0;
        _rtmp34 = input.readListBegin();
        _etype3 = _rtmp34.etype;
        _size0 = _rtmp34.size;
        for (var _i5 = 0; _i5 < _size0; ++_i5)
        {
          var elem6 = null;
          elem6 = input.readI32();
          this.success.push(elem6);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ex = new ttypes.SocialException();
        this.ex.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SocialCoffee.Thrift.SocialCoffeeService_get_friends_result.prototype.write = function(output) {
  output.writeStructBegin('SocialCoffeeService_get_friends_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.I32, this.success.length);
    for (var iter7 in this.success)
    {
      if (this.success.hasOwnProperty(iter7))
      {
        iter7 = this.success[iter7];
        output.writeI32(iter7);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  if (this.ex !== null && this.ex !== undefined) {
    output.writeFieldBegin('ex', Thrift.Type.STRUCT, 1);
    this.ex.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

SocialCoffee.Thrift.SocialCoffeeService_create_friendship_args = function(args) {
  this.usera = null;
  this.userb = null;
  if (args) {
    if (args.usera !== undefined) {
      this.usera = args.usera;
    }
    if (args.userb !== undefined) {
      this.userb = args.userb;
    }
  }
};
SocialCoffee.Thrift.SocialCoffeeService_create_friendship_args.prototype = {};
SocialCoffee.Thrift.SocialCoffeeService_create_friendship_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.usera = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.userb = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SocialCoffee.Thrift.SocialCoffeeService_create_friendship_args.prototype.write = function(output) {
  output.writeStructBegin('SocialCoffeeService_create_friendship_args');
  if (this.usera !== null && this.usera !== undefined) {
    output.writeFieldBegin('usera', Thrift.Type.I32, 1);
    output.writeI32(this.usera);
    output.writeFieldEnd();
  }
  if (this.userb !== null && this.userb !== undefined) {
    output.writeFieldBegin('userb', Thrift.Type.I32, 2);
    output.writeI32(this.userb);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

SocialCoffee.Thrift.SocialCoffeeService_create_friendship_result = function(args) {
  this.success = null;
  this.ex = null;
  if (args instanceof ttypes.SocialException) {
    this.ex = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.ex !== undefined) {
      this.ex = args.ex;
    }
  }
};
SocialCoffee.Thrift.SocialCoffeeService_create_friendship_result.prototype = {};
SocialCoffee.Thrift.SocialCoffeeService_create_friendship_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.BOOL) {
        this.success = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ex = new ttypes.SocialException();
        this.ex.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SocialCoffee.Thrift.SocialCoffeeService_create_friendship_result.prototype.write = function(output) {
  output.writeStructBegin('SocialCoffeeService_create_friendship_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
    output.writeBool(this.success);
    output.writeFieldEnd();
  }
  if (this.ex !== null && this.ex !== undefined) {
    output.writeFieldBegin('ex', Thrift.Type.STRUCT, 1);
    this.ex.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

SocialCoffee.Thrift.SocialCoffeeService_remove_friendship_args = function(args) {
  this.usera = null;
  this.userb = null;
  if (args) {
    if (args.usera !== undefined) {
      this.usera = args.usera;
    }
    if (args.userb !== undefined) {
      this.userb = args.userb;
    }
  }
};
SocialCoffee.Thrift.SocialCoffeeService_remove_friendship_args.prototype = {};
SocialCoffee.Thrift.SocialCoffeeService_remove_friendship_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.usera = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.userb = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SocialCoffee.Thrift.SocialCoffeeService_remove_friendship_args.prototype.write = function(output) {
  output.writeStructBegin('SocialCoffeeService_remove_friendship_args');
  if (this.usera !== null && this.usera !== undefined) {
    output.writeFieldBegin('usera', Thrift.Type.I32, 1);
    output.writeI32(this.usera);
    output.writeFieldEnd();
  }
  if (this.userb !== null && this.userb !== undefined) {
    output.writeFieldBegin('userb', Thrift.Type.I32, 2);
    output.writeI32(this.userb);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

SocialCoffee.Thrift.SocialCoffeeService_remove_friendship_result = function(args) {
  this.success = null;
  this.ex = null;
  if (args instanceof ttypes.SocialException) {
    this.ex = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.ex !== undefined) {
      this.ex = args.ex;
    }
  }
};
SocialCoffee.Thrift.SocialCoffeeService_remove_friendship_result.prototype = {};
SocialCoffee.Thrift.SocialCoffeeService_remove_friendship_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.BOOL) {
        this.success = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ex = new ttypes.SocialException();
        this.ex.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SocialCoffee.Thrift.SocialCoffeeService_remove_friendship_result.prototype.write = function(output) {
  output.writeStructBegin('SocialCoffeeService_remove_friendship_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
    output.writeBool(this.success);
    output.writeFieldEnd();
  }
  if (this.ex !== null && this.ex !== undefined) {
    output.writeFieldBegin('ex', Thrift.Type.STRUCT, 1);
    this.ex.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

SocialCoffee.Thrift.SocialCoffeeServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
SocialCoffee.Thrift.SocialCoffeeServiceClient.prototype = {};
SocialCoffee.Thrift.SocialCoffeeServiceClient.prototype.seqid = function() { return this._seqid; }
SocialCoffee.Thrift.SocialCoffeeServiceClient.prototype.new_seqid = function() { return this._seqid += 1; }
SocialCoffee.Thrift.SocialCoffeeServiceClient.prototype.get_friends = function(id, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_get_friends(id);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_get_friends(id);
  }
};

SocialCoffee.Thrift.SocialCoffeeServiceClient.prototype.send_get_friends = function(id) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('get_friends', Thrift.MessageType.CALL, this.seqid());
  var args = new SocialCoffee.Thrift.SocialCoffeeService_get_friends_args();
  args.id = id;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

SocialCoffee.Thrift.SocialCoffeeServiceClient.prototype.recv_get_friends = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new SocialCoffee.Thrift.SocialCoffeeService_get_friends_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.ex) {
    return callback(result.ex);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('get_friends failed: unknown result');
};
SocialCoffee.Thrift.SocialCoffeeServiceClient.prototype.create_friendship = function(usera, userb, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_create_friendship(usera, userb);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_create_friendship(usera, userb);
  }
};

SocialCoffee.Thrift.SocialCoffeeServiceClient.prototype.send_create_friendship = function(usera, userb) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('create_friendship', Thrift.MessageType.CALL, this.seqid());
  var args = new SocialCoffee.Thrift.SocialCoffeeService_create_friendship_args();
  args.usera = usera;
  args.userb = userb;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

SocialCoffee.Thrift.SocialCoffeeServiceClient.prototype.recv_create_friendship = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new SocialCoffee.Thrift.SocialCoffeeService_create_friendship_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.ex) {
    return callback(result.ex);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('create_friendship failed: unknown result');
};
SocialCoffee.Thrift.SocialCoffeeServiceClient.prototype.remove_friendship = function(usera, userb, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_remove_friendship(usera, userb);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_remove_friendship(usera, userb);
  }
};

SocialCoffee.Thrift.SocialCoffeeServiceClient.prototype.send_remove_friendship = function(usera, userb) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('remove_friendship', Thrift.MessageType.CALL, this.seqid());
  var args = new SocialCoffee.Thrift.SocialCoffeeService_remove_friendship_args();
  args.usera = usera;
  args.userb = userb;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

SocialCoffee.Thrift.SocialCoffeeServiceClient.prototype.recv_remove_friendship = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new SocialCoffee.Thrift.SocialCoffeeService_remove_friendship_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.ex) {
    return callback(result.ex);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('remove_friendship failed: unknown result');
};
SocialCoffee.Thrift.SocialCoffeeServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
SocialCoffee.Thrift.SocialCoffeeServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

SocialCoffee.Thrift.SocialCoffeeServiceProcessor.prototype.process_get_friends = function(seqid, input, output) {
  var args = new SocialCoffee.Thrift.SocialCoffeeService_get_friends_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.get_friends.length === 1) {
    Q.fcall(this._handler.get_friends, args.id)
      .then(function(result) {
        var result = new SocialCoffee.Thrift.SocialCoffeeService_get_friends_result({success: result});
        output.writeMessageBegin("get_friends", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new SocialCoffee.Thrift.SocialCoffeeService_get_friends_result(err);
        output.writeMessageBegin("get_friends", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.get_friends(args.id,  function (err, result) {
      var result = new SocialCoffee.Thrift.SocialCoffeeService_get_friends_result((err != null ? err : {success: result}));
      output.writeMessageBegin("get_friends", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

SocialCoffee.Thrift.SocialCoffeeServiceProcessor.prototype.process_create_friendship = function(seqid, input, output) {
  var args = new SocialCoffee.Thrift.SocialCoffeeService_create_friendship_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.create_friendship.length === 2) {
    Q.fcall(this._handler.create_friendship, args.usera, args.userb)
      .then(function(result) {
        var result = new SocialCoffee.Thrift.SocialCoffeeService_create_friendship_result({success: result});
        output.writeMessageBegin("create_friendship", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new SocialCoffee.Thrift.SocialCoffeeService_create_friendship_result(err);
        output.writeMessageBegin("create_friendship", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.create_friendship(args.usera, args.userb,  function (err, result) {
      var result = new SocialCoffee.Thrift.SocialCoffeeService_create_friendship_result((err != null ? err : {success: result}));
      output.writeMessageBegin("create_friendship", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

SocialCoffee.Thrift.SocialCoffeeServiceProcessor.prototype.process_remove_friendship = function(seqid, input, output) {
  var args = new SocialCoffee.Thrift.SocialCoffeeService_remove_friendship_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.remove_friendship.length === 2) {
    Q.fcall(this._handler.remove_friendship, args.usera, args.userb)
      .then(function(result) {
        var result = new SocialCoffee.Thrift.SocialCoffeeService_remove_friendship_result({success: result});
        output.writeMessageBegin("remove_friendship", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new SocialCoffee.Thrift.SocialCoffeeService_remove_friendship_result(err);
        output.writeMessageBegin("remove_friendship", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.remove_friendship(args.usera, args.userb,  function (err, result) {
      var result = new SocialCoffee.Thrift.SocialCoffeeService_remove_friendship_result((err != null ? err : {success: result}));
      output.writeMessageBegin("remove_friendship", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

