//
// Autogenerated by Thrift Compiler (1.0.0-dev)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('node-thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var fb303_ttypes = require('./fb303_types')


var ttypes = module.exports = {};
if (typeof SocialCoffee === 'undefined') {
  SocialCoffee = {};
}
if (typeof SocialCoffee.Thrift === 'undefined') {
  SocialCoffee.Thrift = {};
}
SocialCoffee.Thrift.SocialException = module.exports.SocialException = function(args) {
  Thrift.TException.call(this, "SocialCoffee.Thrift.SocialException")
  this.name = "SocialCoffee.Thrift.SocialException"
  this.message = null;
  if (args) {
    if (args.message !== undefined) {
      this.message = args.message;
    }
  }
};
Thrift.inherits(SocialCoffee.Thrift.SocialException, Thrift.TException);
SocialCoffee.Thrift.SocialException.prototype.name = 'SocialException';
SocialCoffee.Thrift.SocialException.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.message = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SocialCoffee.Thrift.SocialException.prototype.write = function(output) {
  output.writeStructBegin('SocialException');
  if (this.message !== null && this.message !== undefined) {
    output.writeFieldBegin('message', Thrift.Type.STRING, 1);
    output.writeString(this.message);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ttypes.SOCIAL_COFFEE_VERSION_MAJOR = 1;
ttypes.SOCIAL_COFFEE_VERSION_MINOR = 0;
